ChurchWebsite/Areas/Admin/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Web.Mvc;
using ChurchWebsite.Models;
using System.Globalization;
using Newtonsoft.Json;
using System.Data.Entity.Validation;
using ChurchWebsite.Areas.Admin.Utilities.Data;
using ChurchWebsite.Areas.Admin.Data;

namespace ChurchWebsite.Areas.Admin.Controllers
{
    public class CalendarController : Controller
    {
        private ISiteAdminContext context;

        public CalendarController()
        {
            context = new SiteAdminContext();
        }

        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        [HttpGet]
        public ActionResult _EventDialogue(string evtDate)
        {
            //may have to pass view and have a switch statement as in day view time will be selectable
            CEvent myEvent = new CEvent();
            myEvent.EventDate = DateTime.Parse(evtDate);
            //myEvent.end = DateTime.Parse(evtDate);
            return PartialView("_EventDialogue", myEvent);
        }

        [HttpGet]
        public ActionResult _EventEdit(int evtId, int ignoreRecChk = 0)
        {
            //may have to pass view and have a switch statement as in day view time will be selectable
            var query = from evt in context.CEvents
                        where evt.id == evtId
                        select evt;

            CEvent myEvent = query.First();
            //set not Mapped properties Event Date / StartTime / EndTime
            myEvent.EventDate = DateTime.Parse(myEvent.start.ToString());
            myEvent.StartTime = DateTime.Parse(myEvent.start.ToString()).TimeOfDay;
            myEvent.EndTime = DateTime.Parse(myEvent.end.ToString()).TimeOfDay;
            //clear the time of the event
            myEvent.EventDate = myEvent.EventDate.Subtract(myEvent.EventDate.TimeOfDay);
            if (myEvent.recurranceType != 0 && ignoreRecChk != 1)
            {
                return PartialView("_RecurrancePartial", myEvent);
            }
            return PartialView("_EventDialogue", myEvent);
        }

        [HttpGet]
        public ActionResult _EventCreateInstance(int evtId, string evtDate)
        {
            var query = from evt in context.CEvents
                        where evt.id == evtId
                        select evt;
            //clone the event
            CEvent myEvent = query.First();
            CEvent myClonedEvent = myEvent.DeepCopy();
            //set the recurring to false
            myClonedEvent.Recurring = false;
            myClonedEvent.recurranceType = (int)Recurrance.None;
            //the existence of this ref will also hide recurrance options from the form
            myClonedEvent.recurranceRef = myEvent.id;

            myClonedEvent.EventDate = DateTime.Parse(evtDate);
            //reset the start and end datetime values

            string myNewStartDate = myClonedEvent.EventDate.ToShortDateString() + " " + DateTime.Parse(myEvent.start.ToString()).ToShortTimeString();
            myClonedEvent.start = DateTime.Parse(myNewStartDate);

            string myNewEndDate = myClonedEvent.EventDate.ToShortDateString() + " " + DateTime.Parse(myEvent.end.ToString()).ToShortTimeString();
            myClonedEvent.end = DateTime.Parse(myNewEndDate);

            myClonedEvent.id = context.CEvents.OrderByDescending(evt => evt.id).FirstOrDefault().id + 1;

            int myNewEventId;
            try
            {
                context.Add<CEvent>(myClonedEvent);
                myNewEventId = context.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:", eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"", ve.PropertyName, ve.ErrorMessage);
                        ModelState.AddModelError(ve.PropertyName, ve.ErrorMessage);
                    }
                }
            }

            return PartialView("_EventDialogue", myClonedEvent);
        }

        [HttpGet]
        public object MonthEvents(string start, string end, string currentDate) // Not List<Item> 
        {
            List<CEvent> events;
            List<CEvent> recurringEvents;
            CRecurringEventFilter myRecurringEventFilter;
            
            DateTime myStartParam = DateTime.ParseExact(start, "yyyy-MM-dd", CultureInfo.CurrentCulture);
            DateTime myEndParam = DateTime.ParseExact(end, "yyyy-MM-dd", CultureInfo.CurrentCulture);

            int currentMonth;

            //DateTime myStartParam = new DateTime(1970, 1, 1).AddSeconds(int.Parse(start));
            //DateTime myEndParam = new DateTime(1970, 1, 1).AddSeconds(int.Parse(end));

            //Sort out the current month
            if (myStartParam.Month + 2 == myEndParam.Month)
            {
                currentMonth = myStartParam.Month + 1;
            }
            else
            {
                currentMonth = myStartParam.Month;
            }

            if (myStartParam.Month > myEndParam.Month)
            {
                currentMonth = 12;
            }

            if (myStartParam.Month == 12 && myEndParam.Month < 12)
            {
                currentMonth = 1;
            }

            events = (from evt in context.CEvents
                      where evt.start.Value >= myStartParam && evt.end.Value <= myEndParam && evt.recurranceType == 0
                      select evt).ToList();

            recurringEvents = (from evt in context.CEvents
                               where evt.recurranceType > 0 && myEndParam >= evt.start.Value
                               select evt).ToList();

            myRecurringEventFilter = new CRecurringEventFilter();
            events = myRecurringEventFilter.AddReurringEventsBetweenDates(myStartParam, myEndParam, currentMonth, events, recurringEvents);

            return Json(JsonConvert.SerializeObject(events), JsonRequestBehavior.AllowGet).Data;
        }

        
        [HttpPost]
        public ActionResult Create(CEvent myEvent)
        {
            //add the times of the the event to the date
            myEvent.start = myEvent.EventDate + myEvent.StartTime;
            myEvent.end = myEvent.EventDate + myEvent.EndTime;

            //add other Event propeties createdBy etc...

            //Do we try and add the image here then do check on model valid state?
            try
            {
                context.Add<CEvent>(myEvent);
                context.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    //Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                    //eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        //Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                        //ve.PropertyName, ve.ErrorMessage);
                        ModelState.AddModelError(ve.PropertyName, ve.ErrorMessage);
                    }
                }
            }

            if (!ModelState.IsValid)
            {
                return PartialView("_EventDialogue", myEvent);
            }
            else
            {
                var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index", "Home");
                return Json(new { Url = redirectUrl });
            }
        }

        [HttpPost]
        public ActionResult Update(CEvent myEvent, HttpPostedFileBase image)
        {
            //have IEvent then determine whether or not event is recurring
            //add the times of the the event to the date
            myEvent.start = myEvent.EventDate + myEvent.StartTime;
            myEvent.end = myEvent.EventDate + myEvent.EndTime;

            if (!ModelState.IsValid)
            {
                return PartialView("_EventDialogue", myEvent);
            }
            else
            {
                //if (image != null)
                //{
                //photo.ImageMimeType = image.ContentType;
                //photo.PhotoFile = new byte[image.ContentLength];
                //image.InputStream.Read(photo.PhotoFile, 0, image.ContentLength);
                //}
                //
                CEvent original = context.FindEventById(myEvent.id);
                if (original != null)
                {
                    //context.Entry(original).CurrentValues.SetValues(myEvent);
                    context.Update(original, myEvent);
                    context.SaveChanges();
                }
                var redirectUrl = new UrlHelper(Request.RequestContext).Action("ManageEvents", "Home");
                return Json(new { Url = redirectUrl });
            }
        }

        [HttpGet]
        public ActionResult _DeleteEventRequested(int evtId)
        {
            CEvent myEvent = context.FindEventById(evtId);
            if (myEvent == null)
            {
                return HttpNotFound();
            }
            return PartialView("_EventDeleteConfirm", myEvent);
        }

        [HttpPost]
        public ActionResult _DeleteEvent(int id)
        {
            CEvent myEvent = context.FindEventById(id);

            //check for recurrane ref
            if (myEvent.recurranceRef != null)
            {
                myEvent.cancelled = true;
                context.SaveChanges();
            }

ChurchWebsite/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChurchWebsite.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Beliefs()
        {
            //return View();
            return Redirect(Url.RouteUrl(new { controller = "About", action = "Index" }) + "#Beliefs");
        }

        public ActionResult Vision()
        {
            //return View();
            return Redirect(Url.RouteUrl(new { controller = "About", action = "Index" }) + "#Vision");
        }

        public ActionResult MinistryTeam()
        {
            //return View();
            return Redirect(Url.RouteUrl(new { controller = "About", action = "Index" }) + "#MinistryTeam");
        }

        public ActionResult History()
        {
            //return View();
            return Redirect(Url.RouteUrl(new { controller = "About", action = "Index" }) + "#History");
        }

        public ActionResult Testimonies()
        {
            //return View();
            return Redirect(Url.RouteUrl(new { controller = "About", action = "Index" }) + "#Testimonies");
        }

        public ActionResult DeclarationOfFaith()
        {
            //return View();
            return Redirect(Url.RouteUrl(new { controller = "About", action = "Index" }) + "#DeclarationOfFaith");
        }
    }
}

ChurchWebsite/Areas/Admin/Views/Calendar/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

ChurchWebsite/Areas/Admin/Views/Calendar/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

ChurchWebsite/Areas/Admin/Views/Calendar/PartialTest.cshtml
<h1>This is a Test Partial View</h1>

ChurchWebsite/Areas/Admin/Views/Calendar/_EventDeleteConfirm.cshtml
@model ChurchWebsite.Models.CEvent
<p>Are you sure want to delete the event @Model.title?</p>

ChurchWebsite/Areas/Admin/Views/Calendar/_EventDialogue.cshtml
@using PerpetuumSoft.Knockout
@using ChurchWebsite.Models
@using ChurchWebsite.Areas.Admin.Extensions
@model ChurchWebsite.Models.CEvent

<script type="text/javascript">
    var viewModel = new DynamicModelLoading(@Html.Raw(Model.ToJson()));
    ko.applyBindings(viewModel);
</script>


<div id="dialog" title="Basic dialog" class="eventDialogue">
    <div id="eventFormHolder">
    @if (Model.id == 0)
    {
        <h2>New Event</h2>
    }
    else
    {
        <h2>Edit Event</h2>
    }
    
        @using (Ajax.BeginForm(Model.id == 0 ? "Create" : "Update", "Calendar", new AjaxOptions{ InsertionMode = InsertionMode.Replace,//target element(#pacientList) will be replace)))
                                                                                                UpdateTargetId = "eventFormHolder", OnSuccess = "onEventFormSubmissionSuccess", HttpMethod = "POST"
                                                                                                    @*LoadingElementId = "loader" //div with .gif loader*@}))
        {
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.id)
            <p>@Html.TextBoxFor(model => model.EventDate)</p>
            <div class="dialogFormElement">
                @Html.LabelFor(model => model.title)&nbsp;:@Html.EditorFor(model => model.title)
            </div>
            <div class="dialogFormValidation">
                @Html.ValidationMessageFor(model => model.title)
            </div>
            <div class="dialogFormElement">
                @Html.LabelFor(model => model.description)&nbsp;:@Html.EditorFor(model => model.description)
            </div>
            <div class="dialogFormValidation">
                @Html.ValidationMessageFor(model => model.description)
            </div>
            <div class="dialogFormElement" id="m_recurringEventChkBox" data-bind="ifnot: recurranceRef">
                @Html.Label("Recurring Event")&nbsp;:@Html.CheckBoxFor(m => m.Recurring, new { data_bind="checked: Recurring" })
            </div>
            <div class="dialogFormElement" data-bind="visible: Recurring" >
                @Html.Label("Recurance Type")&nbsp;:@Html.DropDownListFor(m => m.recurranceType, Model.CurrentRecurranceOptions)
            </div>
            <div class="dialogFormElement">
                @Html.LabelFor(model => model.showInCal)&nbsp;:@Html.CheckBoxFor(model => model.showInCal)
            </div>
            <div class="dialogFormElement">
                @Html.LabelFor(model => model.showOnHome)&nbsp;:@Html.CheckBoxFor(model => model.showOnHome, new { data_bind="checked: showOnHome" })
            </div>
            @Html.HiddenFor(model => model.imgId, new {data_bind="value: imgId"})
            <div class="dialogFormElement">
                <input readonly="true" type="text"/>
                <input type="button" id="imgLib_button" value="Choose Image" />
            </div>
            <div class="dialogFormValidation">
                @Html.ValidationMessageFor(model => model.imgId)
            </div>
            <div id="imagePlaceholder"/>
            <div class="dialogFormElement">
                @Html.LabelFor(model => model.allDay)&nbsp;:@Html.CheckBoxFor(m => m.allDay, new { data_bind="checked: allDay"})
            </div>
            <div class="dialogFormElement" data-bind="visible: !allDay()")>
                @Html.LabelFor(model => model.start)&nbsp;:@Html.EditorFor(model => model.StartTime)
            </div>
            <div class="dialogFormValidation">
                @Html.ValidationMessageFor(model => model.StartTime)
            </div>
            <div id="m_endTimeDiv" class="dialogFormElement" data-bind="visible: !allDay()">
                @Html.LabelFor(model => model.end)&nbsp;:@Html.EditorFor(model => model.EndTime)
            </div>
            <div class="dialogFormValidation">
                @Html.ValidationMessageFor(model => model.EndTime)
            </div>
            <div class="dialogFormElement" data-bind="visible: showOnHome">
                @Html.LabelFor(model => model.url)&nbsp;:@Html.EditorFor(model => model.url)
            </div>
        }
    </div>
</div>
<div id="imageLib" />
<div id="eventDeleteDialog" />

ChurchWebsite/Areas/Admin/Views/Calendar/_RecurrancePartial.cshtml
@using PerpetuumSoft.Knockout
@using ChurchWebsite.Areas.Admin.Extensions
@model ChurchWebsite.Models.CEvent

<script type="text/javascript">
    var viewModel = new DynamicModelLoading(@Html.Raw(Model.ToJson()));
    ko.applyBindings(viewModel);
</script>

<p>The event you are editing is a recurring event beginning @string.Format("{0:dd/MM/yyyy}", Model.start)</p>
<p>Do you want to edit every occurance of this event or just this instance?</p>

ChurchWebsite/Areas/Admin/Views/Calendar/_UploadImage.cshtml
<div>
    <h2>Create New Photo</h2>
    @Html.Action("_ImageUploadForm", "Home")
</div>